-- ============================================================================
--  WolffMsg — схема базы для Supabase (PostgreSQL)
--
--  Запустить один раз в Supabase → SQL Editor → New query → Run.
--  Скрипт идемпотентный: его можно выполнять повторно и на уже существующей
--  базе — данные не удаляются, недостающие таблицы и колонки добавляются.
-- ============================================================================

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------- профили ---
create table if not exists public.profiles (
    id            text primary key,
    nickname      text not null,
    name          text not null default '',
    avatar        text default '',
    password      text,             -- устаревшее поле (открытый пароль)
    password_hash text,             -- bcrypt-хеш, используется начиная с v49
    created_at    timestamptz not null default now()
);

alter table public.profiles add column if not exists name          text not null default '';
alter table public.profiles add column if not exists avatar        text default '';
alter table public.profiles add column if not exists password_hash text;
alter table public.profiles add column if not exists created_at    timestamptz not null default now();

update public.profiles set nickname = lower(nickname) where nickname <> lower(nickname);

create unique index if not exists profiles_nickname_key on public.profiles (lower(nickname));

-- ------------------------------------------------------------------ чаты ---
create table if not exists public.chats (
    room_id    text primary key,
    name       text not null default '',
    kind       text not null default 'dm',        -- 'dm' | 'group'
    members    text[] not null default '{}',
    created_at timestamptz not null default now()
);

create index if not exists chats_members_idx on public.chats using gin (members);

-- ------------------------------------------------------------- сообщения ---
create table if not exists public.messages (
    id         bigint generated by default as identity primary key,
    room_id    text not null,
    user_id    text,
    user_name  text,
    text       text,
    reactions  jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.messages add column if not exists reactions  jsonb not null default '{}'::jsonb;
alter table public.messages add column if not exists created_at timestamptz not null default now();
alter table public.messages add column if not exists user_name  text;

create index if not exists messages_room_time_idx on public.messages (room_id, created_at desc);

-- --------------------------------------------------- отметки о прочтении ---
create table if not exists public.room_reads (
    room_id      text not null,
    user_id      text not null,
    last_read_at timestamptz not null default now(),
    primary key (room_id, user_id)
);

-- ------------------------------------- превью последнего сообщения чата ---
create or replace view public.chat_previews as
select distinct on (m.room_id)
    m.room_id,
    m.id,
    m.user_id,
    m.user_name,
    case
        when m.text like 'data:image/%' then '📷 Фото'
        else left(coalesce(m.text, ''), 120)
    end as preview,
    m.created_at
from public.messages m
order by m.room_id, m.created_at desc;

-- ============================================================================
--  Функции входа и регистрации.
--  Пароли хранятся только в виде bcrypt-хеша; клиент никогда не читает их.
-- ============================================================================

create or replace function public.wm_public_user(p public.profiles)
returns json language sql immutable as $$
    select json_build_object('id', p.id, 'nickname', p.nickname, 'name', p.name, 'avatar', coalesce(p.avatar, ''));
$$;

create or replace function public.wm_register(p_nickname text, p_password text, p_name text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_nick text := lower(trim(both ' ' from coalesce(p_nickname, '')));
    v_row  public.profiles;
begin
    if v_nick !~ '^[a-z0-9_.]{3,32}$' then
        return json_build_object('ok', false, 'error', 'bad_nickname');
    end if;
    if coalesce(length(p_password), 0) < 4 then
        return json_build_object('ok', false, 'error', 'weak_password');
    end if;
    if exists (select 1 from public.profiles where lower(nickname) = v_nick) then
        return json_build_object('ok', false, 'error', 'nickname_taken');
    end if;

    insert into public.profiles (id, nickname, name, avatar, password_hash)
    values ('u' || floor(extract(epoch from now()) * 1000)::bigint || floor(random() * 1000)::int,
            v_nick,
            nullif(trim(both ' ' from coalesce(p_name, '')), ''),
            '',
            crypt(p_password, gen_salt('bf')))
    returning * into v_row;

    update public.profiles set name = v_nick where id = v_row.id and (name is null or name = '');
    select * into v_row from public.profiles where id = v_row.id;

    return json_build_object('ok', true, 'user', public.wm_public_user(v_row));
end;
$$;

create or replace function public.wm_login(p_nickname text, p_password text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_row public.profiles;
begin
    select * into v_row from public.profiles
     where lower(nickname) = lower(trim(both ' ' from coalesce(p_nickname, '')))
     limit 1;

    if v_row.id is null then
        return json_build_object('ok', false, 'error', 'not_found');
    end if;

    if v_row.password_hash is not null then
        if v_row.password_hash = crypt(p_password, v_row.password_hash) then
            return json_build_object('ok', true, 'user', public.wm_public_user(v_row));
        end if;
        return json_build_object('ok', false, 'error', 'bad_password');
    end if;

    -- миграция со старой схемы: пароль лежал открытым текстом
    if v_row.password is not null and v_row.password = p_password then
        update public.profiles
           set password_hash = crypt(p_password, gen_salt('bf')), password = null
         where id = v_row.id;
        return json_build_object('ok', true, 'user', public.wm_public_user(v_row));
    end if;

    return json_build_object('ok', false, 'error', 'bad_password');
end;
$$;

create or replace function public.wm_set_password(p_nickname text, p_old_password text, p_new_password text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
    v_check json;
    v_row   public.profiles;
begin
    if coalesce(length(p_new_password), 0) < 4 then
        return json_build_object('ok', false, 'error', 'weak_password');
    end if;

    v_check := public.wm_login(p_nickname, p_old_password);
    if (v_check ->> 'ok')::boolean is not true then
        return json_build_object('ok', false, 'error', 'bad_password');
    end if;

    update public.profiles
       set password_hash = crypt(p_new_password, gen_salt('bf')), password = null
     where lower(nickname) = lower(p_nickname)
    returning * into v_row;

    return json_build_object('ok', true, 'user', public.wm_public_user(v_row));
end;
$$;

-- ============================================================================
--  Права доступа
--
--  ВАЖНО: приложение обращается к базе публичным anon-ключом. Пароли закрыты
--  полностью (их отдаёт только функция входа), остальные данные доступны
--  любому, у кого есть ключ. Для приватной переписки переходите на
--  Supabase Auth + политики по auth.uid().
-- ============================================================================

alter table public.profiles   enable row level security;
alter table public.chats      enable row level security;
alter table public.messages   enable row level security;
alter table public.room_reads enable row level security;

drop policy if exists wm_profiles_read   on public.profiles;
drop policy if exists wm_profiles_write  on public.profiles;
drop policy if exists wm_chats_all       on public.chats;
drop policy if exists wm_messages_all    on public.messages;
drop policy if exists wm_reads_all       on public.room_reads;

create policy wm_profiles_read  on public.profiles   for select using (true);
create policy wm_profiles_write on public.profiles   for update using (true) with check (true);
create policy wm_chats_all      on public.chats      for all    using (true) with check (true);
create policy wm_messages_all   on public.messages   for all    using (true) with check (true);
create policy wm_reads_all      on public.room_reads for all    using (true) with check (true);

-- профили: читать можно только безопасные колонки, менять — имя и аватар
revoke all on public.profiles from anon, authenticated;
grant select (id, nickname, name, avatar, created_at) on public.profiles to anon, authenticated;
grant update (name, avatar)                           on public.profiles to anon, authenticated;
grant delete                                          on public.profiles to anon, authenticated;

grant select, insert, update, delete on public.chats      to anon, authenticated;
grant select, insert, update, delete on public.messages   to anon, authenticated;
grant select, insert, update, delete on public.room_reads to anon, authenticated;
grant select                         on public.chat_previews to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

grant execute on function public.wm_register(text, text, text)          to anon, authenticated;
grant execute on function public.wm_login(text, text)                   to anon, authenticated;
grant execute on function public.wm_set_password(text, text, text)      to anon, authenticated;

-- Supabase Realtime (необязательно): мгновенная доставка вместо опроса
-- alter publication supabase_realtime add table public.messages;

-- ============================================================================
--  Обновление кеша REST API.
--
--  PostgREST держит список таблиц и функций в памяти и не всегда подхватывает
--  изменения сразу. Без этой команды приложение может некоторое время получать
--  404 на wm_register / wm_login и падать с ошибкой
--  «permission denied for table profiles».
--
--  Если ошибка всё же появилась — выполните эту строку отдельно и подождите
--  около минуты.
-- ============================================================================

notify pgrst, 'reload schema';
