-- ============================================================================
--  WolffMsg — схема базы для Supabase (PostgreSQL)
--
--  Запустить в Supabase → SQL Editor → New query → Run.
--
--  Скрипт безопасен для существующей базы: ничего не удаляется, недостающее
--  добавляется. Все шаги, способные завершиться ошибкой на «грязных» данных,
--  обёрнуты в блоки с перехватом ошибок — Supabase выполняет скрипт одной
--  транзакцией, и одна упавшая строка иначе откатывала бы всю установку.
--
--  В самом конце скрипт печатает отчёт: сколько функций создано и открыт ли
--  доступ. Если что-то пошло не так — смотрите NOTICE в выводе.
-- ============================================================================

-- ------------------------------------------------- расширение для паролей ---
-- В Supabase расширения ставятся в схему extensions, в «голом» PostgreSQL —
-- в public. Поддерживаем оба варианта.
create schema if not exists extensions;

do $$
begin
    if not exists (select 1 from pg_extension where extname = 'pgcrypto') then
        begin
            execute 'create extension pgcrypto with schema extensions';
        exception when others then
            execute 'create extension pgcrypto';
        end;
    end if;
end $$;

-- ---------------------------------------------------------------- профили ---
create table if not exists public.profiles (
    id            text primary key,
    nickname      text not null,
    name          text not null default '',
    avatar        text default '',
    password      text,             -- устаревшее поле (открытый пароль)
    password_hash text,             -- bcrypt-хеш, используется начиная с v49
    created_at    timestamptz not null default now()
);

alter table public.profiles add column if not exists name          text;
alter table public.profiles add column if not exists avatar        text;
alter table public.profiles add column if not exists password      text;
alter table public.profiles add column if not exists password_hash text;
alter table public.profiles add column if not exists created_at    timestamptz default now();

update public.profiles set name = coalesce(nullif(name, ''), nickname) where name is null or name = '';
update public.profiles set avatar = coalesce(avatar, '') where avatar is null;
update public.profiles set created_at = now() where created_at is null;

-- Приводим ники к нижнему регистру и разводим совпадения: без этого шага
-- уникальный индекс ниже падает, а вместе с ним откатывается весь скрипт.
do $$
declare
    dup record;
    other text;
    n int;
begin
    update public.profiles
       set nickname = lower(trim(both ' ' from nickname))
     where nickname is distinct from lower(trim(both ' ' from nickname));

    for dup in
        select nickname, array_agg(id order by created_at nulls last, id) as ids
          from public.profiles
         group by nickname
        having count(*) > 1
    loop
        n := 1;
        -- первый владелец ника остаётся как есть, остальным добавляем номер
        foreach other in array dup.ids[2:array_length(dup.ids, 1)]
        loop
            n := n + 1;
            update public.profiles
               set nickname = dup.nickname || n::text
             where id = other;
            raise notice 'Ник «%» повторялся: профиль % переименован в «%»',
                dup.nickname, other, dup.nickname || n::text;
        end loop;
    end loop;
exception when others then
    raise notice 'Не удалось развести повторяющиеся ники: %', sqlerrm;
end $$;

do $$
begin
    create unique index if not exists profiles_nickname_key on public.profiles (nickname);
exception when others then
    raise notice 'Уникальный индекс по нику не создан: %', sqlerrm;
end $$;

-- ------------------------------------------------------------------ чаты ---
create table if not exists public.chats (
    room_id    text primary key,
    name       text not null default '',
    kind       text not null default 'dm',        -- 'dm' | 'group'
    members    text[] not null default '{}',
    created_at timestamptz not null default now()
);

do $$
begin
    create index if not exists chats_members_idx on public.chats using gin (members);
exception when others then
    raise notice 'Индекс по участникам чата не создан: %', sqlerrm;
end $$;

-- ------------------------------------------------------------- сообщения ---
create table if not exists public.messages (
    id         bigint generated by default as identity primary key,
    room_id    text not null,
    user_id    text,
    user_name  text,
    text       text,
    reactions  jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

alter table public.messages add column if not exists reactions  jsonb default '{}'::jsonb;
alter table public.messages add column if not exists created_at timestamptz default now();
alter table public.messages add column if not exists user_name  text;

update public.messages set reactions = '{}'::jsonb where reactions is null;

do $$
begin
    create index if not exists messages_room_time_idx on public.messages (room_id, created_at desc);
exception when others then
    raise notice 'Индекс по сообщениям не создан: %', sqlerrm;
end $$;

-- --------------------------------------------------- отметки о прочтении ---
create table if not exists public.room_reads (
    room_id      text not null,
    user_id      text not null,
    last_read_at timestamptz not null default now(),
    primary key (room_id, user_id)
);

-- ------------------------------------- превью последнего сообщения чата ---
create or replace view public.chat_previews as
select distinct on (m.room_id)
    m.room_id,
    m.id,
    m.user_id,
    m.user_name,
    case
        when m.text like 'data:image/%' then '📷 Фото'
        else left(coalesce(m.text, ''), 120)
    end as preview,
    m.created_at
from public.messages m
order by m.room_id, m.created_at desc;

-- ============================================================================
--  Функции входа и регистрации.
--  Пароли хранятся только в виде bcrypt-хеша; клиент их не читает.
--  search_path включает extensions — там в Supabase живёт pgcrypto.
-- ============================================================================

create or replace function public.wm_public_user(p public.profiles)
returns json language sql immutable as $$
    select json_build_object('id', p.id, 'nickname', p.nickname,
                             'name', coalesce(nullif(p.name, ''), p.nickname),
                             'avatar', coalesce(p.avatar, ''));
$$;

create or replace function public.wm_register(p_nickname text, p_password text, p_name text)
returns json
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
    v_nick text := lower(trim(both ' ' from coalesce(p_nickname, '')));
    v_row  public.profiles;
begin
    if v_nick !~ '^[a-z0-9_.]{3,32}$' then
        return json_build_object('ok', false, 'error', 'bad_nickname');
    end if;
    if coalesce(length(p_password), 0) < 4 then
        return json_build_object('ok', false, 'error', 'weak_password');
    end if;
    if exists (select 1 from public.profiles where nickname = v_nick) then
        return json_build_object('ok', false, 'error', 'nickname_taken');
    end if;

    insert into public.profiles (id, nickname, name, avatar, password_hash)
    values ('u' || floor(extract(epoch from now()) * 1000)::bigint || floor(random() * 1000)::int,
            v_nick,
            coalesce(nullif(trim(both ' ' from coalesce(p_name, '')), ''), v_nick),
            '',
            crypt(p_password, gen_salt('bf')))
    returning * into v_row;

    return json_build_object('ok', true, 'user', public.wm_public_user(v_row));
end;
$$;

create or replace function public.wm_login(p_nickname text, p_password text)
returns json
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
    v_row public.profiles;
begin
    select * into v_row from public.profiles
     where nickname = lower(trim(both ' ' from coalesce(p_nickname, '')))
     limit 1;

    if v_row.id is null then
        return json_build_object('ok', false, 'error', 'not_found');
    end if;

    if v_row.password_hash is not null then
        if v_row.password_hash = crypt(p_password, v_row.password_hash) then
            return json_build_object('ok', true, 'user', public.wm_public_user(v_row));
        end if;
        return json_build_object('ok', false, 'error', 'bad_password');
    end if;

    -- миграция со старой схемы: пароль лежал открытым текстом
    if v_row.password is not null and v_row.password = p_password then
        update public.profiles
           set password_hash = crypt(p_password, gen_salt('bf')), password = null
         where id = v_row.id;
        return json_build_object('ok', true, 'user', public.wm_public_user(v_row));
    end if;

    return json_build_object('ok', false, 'error', 'bad_password');
end;
$$;

create or replace function public.wm_set_password(p_nickname text, p_old_password text, p_new_password text)
returns json
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
    v_check json;
    v_row   public.profiles;
begin
    if coalesce(length(p_new_password), 0) < 4 then
        return json_build_object('ok', false, 'error', 'weak_password');
    end if;

    v_check := public.wm_login(p_nickname, p_old_password);
    if (v_check ->> 'ok')::boolean is not true then
        return json_build_object('ok', false, 'error', 'bad_password');
    end if;

    update public.profiles
       set password_hash = crypt(p_new_password, gen_salt('bf')), password = null
     where nickname = lower(trim(both ' ' from p_nickname))
    returning * into v_row;

    return json_build_object('ok', true, 'user', public.wm_public_user(v_row));
end;
$$;

-- ============================================================================
--  Права доступа
--
--  ВАЖНО: приложение обращается к базе публичным ключом anon. Пароли закрыты
--  полностью (их проверяет только функция входа), остальные данные доступны
--  любому, у кого есть ключ. Для приватной переписки нужен переход на
--  Supabase Auth с политиками по auth.uid().
-- ============================================================================

alter table public.profiles   enable row level security;
alter table public.chats      enable row level security;
alter table public.messages   enable row level security;
alter table public.room_reads enable row level security;

drop policy if exists wm_profiles_read   on public.profiles;
drop policy if exists wm_profiles_write  on public.profiles;
drop policy if exists wm_chats_all       on public.chats;
drop policy if exists wm_messages_all    on public.messages;
drop policy if exists wm_reads_all       on public.room_reads;

create policy wm_profiles_read  on public.profiles   for select using (true);
create policy wm_profiles_write on public.profiles   for update using (true) with check (true);
create policy wm_chats_all      on public.chats      for all    using (true) with check (true);
create policy wm_messages_all   on public.messages   for all    using (true) with check (true);
create policy wm_reads_all      on public.room_reads for all    using (true) with check (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.chats         to anon, authenticated;
grant select, insert, update, delete on public.messages      to anon, authenticated;
grant select, insert, update, delete on public.room_reads    to anon, authenticated;
grant select                         on public.chat_previews to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

grant execute on function public.wm_register(text, text, text)     to anon, authenticated;
grant execute on function public.wm_login(text, text)              to anon, authenticated;
grant execute on function public.wm_set_password(text, text, text) to anon, authenticated;

-- Доступ к profiles закрываем ТОЛЬКО если функции входа действительно созданы.
-- Иначе приложение осталось бы и без функций, и без прямой записи — именно так
-- выглядела ошибка «permission denied for table profiles».
do $$
declare
    v_funcs int;
begin
    select count(*) into v_funcs
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.proname in ('wm_register', 'wm_login');

    if v_funcs >= 2 then
        execute 'revoke all on public.profiles from anon, authenticated';
        execute 'grant select (id, nickname, name, avatar, created_at) on public.profiles to anon, authenticated';
        execute 'grant update (name, avatar) on public.profiles to anon, authenticated';
        execute 'grant delete on public.profiles to anon, authenticated';
        raise notice 'Прямой доступ к паролям закрыт, вход работает через функции.';
    else
        execute 'grant select, insert, update, delete on public.profiles to anon, authenticated';
        raise notice 'ВНИМАНИЕ: функции входа не созданы, оставлен прямой доступ к profiles.';
    end if;
end $$;

-- ============================================================================
--  Обновление кеша REST API. PostgREST держит список таблиц и функций в
--  памяти; без этой команды новые функции какое-то время отдают 404, и
--  приложение сообщает «База ещё не готова принимать регистрацию».
-- ============================================================================

notify pgrst, 'reload schema';

-- ------------------------------------------------------------- отчёт ------
select
    (select count(*) from pg_proc p join pg_namespace n on n.oid = p.pronamespace
      where n.nspname = 'public' and p.proname in ('wm_register', 'wm_login', 'wm_set_password'))
        as "функций создано (нужно 3)",
    (select count(*) from public.profiles)  as "профилей в базе",
    (select count(*) from public.messages)  as "сообщений в базе",
    (select count(*) from information_schema.role_table_grants
      where grantee = 'anon' and table_name = 'messages' and privilege_type = 'INSERT')
        as "anon может писать сообщения";
